server {
    # Nginx écoute sur le port 80
    listen 80;

    # Le dossier racine où se trouvent les fichiers de notre site
    root /usr/share/nginx/html;

    # Le fichier à servir par défaut si l'URL est un répertoire
    index index.html;

    # Configuration pour les SPA
    location / {
        # Cette ligne est la plus importante pour le routage côté client :
        # 1. Essaye de trouver un fichier qui correspond à l'URL ($uri).
        # 2. Si ce n'est pas un fichier, essaye de trouver un dossier ($uri/).
        # 3. Si rien n'est trouvé, renvoie sur /index.html.
        #    Cela permet à votre routeur JavaScript (ex: React Router) de gérer la route.
        try_files $uri $uri/ /index.html;
    }
}